name: Build and Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run node-actionlint
        run: ./bin/node-actionlint.js
